### ISSUE TITLE
figwheel compile error,  Invalid :refer, var re-frame.core/console does not exist 

### ISSUE THREAD

**Issue by dasibre** [Day8/re-frame-http-fx#1]
dependencies:
  [org.clojure/clojurescript "1.9.89"]
  [reagent "0.5.1"]
[re-frame "0.5.0"]
[day8.re-frame/http-fx "0.0.4"]
 Invalid :refer, var re-frame.core/console does not exist

**Comment by mike-thompson-day8** [comment]
As the README notes:  
> Requires re-frame >= v0.8.0-alpha3
which in turn requires reagent 0.6.0

Be slightly cautious.  You are using the alpha end re-frame.  Hopefully no further changes,  but you never know, it isn't beta yet.
