### ISSUE TITLE
README has an error when posting body

### ISSUE THREAD

**Issue by raymcdermott** [Day8/re-frame-http-fx#19]
When using this component to post a body (like a form) there is no need to specify a format, as forcefully stated. The implementation ignores it.

This works fine:

```clojure
(re-frame/reg-event-fx
  :upload-content
  (fn [{:keys [db]} _]
    (let [{:keys [version-name upload-file]} db
          form-data (doto (js/FormData.)
                      (.append "version-name" version-name)
                      (.append "upload-file" upload-file))]
      {:http-xhrio {:method          :post
                    :uri             "http://localhost:3000/api/upload"
                    :body            form-data
                    :timeout         1000
                    :response-format (ajax/json-response-format {:keywords? true})
                    :on-success      [::content-uploaded]
                    :on-failure      [::upload-failed]}})))
```

**Comment by danielcompton** [comment]
Hi Ray, thanks for opening this, I didn't realise this was possible. I think this only applies for FormData parameters, as you need to provide them directly as the `:body`.

> `:body` the exact data to send with in the request. If specified, both `:params` and `:request-format` are ignored. Note that you can submit `js/FormData` and other "raw" javascript types through this. - https://github.com/JulianBirch/cljs-ajax#getpostput

I was mainly going off the docs for (ajax-request)[https://github.com/JulianBirch/cljs-ajax#ajax-request] and didn't even realise that it supported a `:body` param. This lib mainly just proxies args through to cljs-ajax, it might be worth checking there if this is intended usage, and if so adding some docs/tests so people don't accidentally break it for you in the future. Happy to have a docs patch here once we know whether this is intended behaviour or not. Thanks!

**Comment by raymcdermott** [comment]
Hi Daniel - I compared the tests in this repo, specifically xhrio-post-body-test with the ajax-request tests, specifically run-browser-tests. 

In your tests, you use this form:

```clojure
(deftest xhrio-post-body-test
  (async done
    (re-frame/dispatch [::http-test {:method          :post
                                     :uri             "https://httpbin.org/post"
                                     :body            (doto (js/FormData.)
                                                        (.append "username" "bob")
                                                        (.append "password" "sekrit"))
                                     :timeout         5000
                                     :format          (ajax/json-request-format)
                                     :response-format (ajax/json-response-format)
                                     :on-success      [::good-post-body-result done]
:on-failure [::bad-http-result done "test-token1"]}])))
```

In their tests, they use this form:
```clojure
#? (:cljs (ajax-request {:uri "/ajax-form-data-png"
                           :method "POST"
                           :body (doto
                                     (js/FormData.)
                                   (.append "id" "19")
                                   (.append "timeout" "0")
                                   (.append "input" "Hello form-data POST"))
                           :api (js/XMLHttpRequest.)
                           :handler blob-response-handler
                           :error-handler handle-error
                           :response-format {:content-type "image/png"
                                             :type :blob
                                             :description "PNG file"
:read -body}}))
```

So, my deduction was that `format` is indeed not needed for a POST operation when the body is present. This turned out to be the case in practise and I only raised the issue since your docs are strongly suggesting that it is mandatory.

I also shared your concern about understanding whether this is the proper / intended behaviour as their docs on `ajax-request` are by exception. I hope you will agree that their tests are unambiguous.

I can also contact Julian if you remain unconvinced.

In any case, I would be happy to make a small update your tests / README and make a PR. 

What do you think?

**Comment by danielcompton** [comment]
Yep, you're right, I had forgotten about those tests.

> This turned out to be the case in practise and I only raised the issue since your docs are strongly suggesting that it is mandatory.

Yeah, we had a number of people having issues with this library because they didn't realise they needed to provide format and response-format so I made it very obvious, unfortunately I missed the nuance when body is provided.

> In any case, I would be happy to make a small update your tests / README and make a PR.

Yep, that'd be great!

**Comment by raymcdermott** [comment]
Can close this now
