### ISSUE TITLE
GET request does not work with React Native for Android

### ISSUE THREAD

**Issue by mprokopov** [Day8/re-frame-http-fx#23]
Due to issues with Javascript interop, cljs-ajax and React Native for Android, GET requests does not work from android device.

https://github.com/facebook/react-native/issues/3115
https://github.com/JulianBirch/cljs-ajax/issues/155

**Comment by danielcompton** [comment]
I don't think there is much we can do about this in this repo, we rely completely on cljs-ajax for actually doing the requests, so any fix would need to happen there. Thanks for the heads up though. Will close this here, but can track it in JulianBirch/cljs-ajax#155.
