### ISSUE TITLE
compiler warning with clojurescript 1.9.946 -> please bump cljs-ajax version

### ISSUE THREAD

**Issue by raymcdermott** [Day8/re-frame-http-fx#24]
Version 0.1.4 of re-frame-http-fx

```shell
$ lein karma-once
Compiling ClojureScript...
Compiling "resources/public/karma/test.js" from ["test/cljs" "src/cljs"]...
WARNING: uri? already refers to: cljs.core/uri? being replaced by: cognitect.transit/uri? at line 332 resources/public/karma/test/cognitect/transit.cljs
Successfully compiled "resources/public/karma/test.js" in 37.9 seconds.
```

Version 0.1.5-SNAPSHOT of re-frame-http-fx, after I cloned it and bumped cljs-ajax from 0.5.8 to 0.7.3

```shell
$ lein karma-once
Compiling ClojureScript...
Compiling "resources/public/karma/test.js" from ["test/cljs" "src/cljs"]...
Successfully compiled "resources/public/karma/test.js" in 40.251 seconds.
```

I don't want to make a PR out of this as you might have other issues but happy to do so if you like.

**Comment by raymcdermott** [comment]
The issue comes from an outdated version of `transit` in cljs-ajax but the net effect is that you have to bump ;-)

**Comment by danielcompton** [comment]
I've cut a new release in `http-fx-0.1.5-20180130.200601-1` can you give it a go and let me know how you get on? If all is well I'll do a full release.

**Comment by raymcdermott** [comment]
It's a small sample but testing my app (with re-frame-test, karma and manually) all works.

**Comment by danielcompton** [comment]
0.1.5 is out and fixes this. Thanks for the report!
