### ISSUE TITLE
:finally does not work?

### ISSUE THREAD

**Issue by ertugrulcetin** [Day8/re-frame-http-fx#28]
I've added `:finally` keyword to the request map. But it's not getting called.

**Comment by danielcompton** [comment]
I haven't looked at http-fx for a while, so I might be forgetting something, but I don't think this library supports a `:finally` keyword. Did you read some docs somewhere that talked about this?

**Comment by ertugrulcetin** [comment]
@danielcompton It uses ajax.core (_cljs-ajax_) library under the hood, so I thought `:finally` will be supported. Because http-fx creates it's own request-map and hand it to ajax.core.

**Comment by danielcompton** [comment]
Ah, of course. I can't see anything that we're doing that would inhibit the `:finally` from being called. Have you tried stepping through in a debugger to see if the finally is being hit? Can you share a code sample showing how you're calling it?

**Comment by danielcompton** [comment]
Ah, now I think about it, I think that `:finally` might only be supported in the simple API, not the `ajax-request` one that we use.

**Comment by ertugrulcetin** [comment]
Hmm I think if the lib supports core API that would be wonderful. Otherwise we have to provide :finally fn to both `on-success` and `on-fail` fns.

**Comment by danielcompton** [comment]
The lib doesn't support the simple API, and isn't likely to in the near future. For now, providing the `:finally` function is probably your best bet, or you could write a simple adapter for the `GET` and `POST` cljs-ajax functions to turn them into effects. Will close this for now, as there's not much we can do here.
