### ISSUE TITLE
Re-enable and revise specs for request map

### ISSUE THREAD

**Issue by superstructor** [day8/re-frame-http-fx#33]
Specs were commented out in aca153eee67ab15e7ad888297e84d087ca84f7ed

As it has been 3 years, specs maybe considered stable enough nowadays albeit still `clojure.spec.alpha` ns and spec2 is as yet unreleased ?

**Comment by mike-thompson-day8** [comment]
Yeah, while ever still alpha, let's not include.

**Comment by superstructor** [comment]
Ok :+1: Will leave this open to wait until [spec-2](https://github.com/clojure/spec-alpha2) (or subsequent iterations) stabilise.
