### ISSUE TITLE
ajax/json-request-format with namespace keywords

### ISSUE THREAD

**Issue by sirmspencer** [day8/re-frame-http-fx#52]
This request formatter is stripping any leading namespace qualified keywords before writing to json. `{:widget/id 123}` becomes `{:id 123}`.  We are using the qualified keywords in our system.  mitosin on the back end send json response perfectly fine with the ns qualified keywords.  Our current work around is to send to the backend using transit.  However we don't need any of the features of transit and its just making it hard to debug requests from the console.

It looks like its from the default keyword fn in clj->js.  

```
(defn- nsq-keyword-fn [k]
  (let [ns (namespace k)
        n  (name k)]
    (if ns
      (str ns "/" n)
      n)))

(clj->js {:a/b 123} :keyword-fn nsq-keyword-fn) => #js {"a/b" 123}
```

I'm not exactly sure how to stick that into json.cljc as an option to json-request-format.

**Comment by kimo-k** [comment]
Hi, what makes you think this isn't an upstream issue? Can you repro with a direct call to `ajax.core/ajax-request`?

Have you seen https://github.com/JulianBirch/cljs-ajax/issues/260?

Looking at cljs-ajax, it seems like their fix only applied to [url-request-format](https://github.com/JulianBirch/cljs-ajax/blob/359e83ca0cd628c22252ba861860cb921622a618/src/ajax/url.cljc#L126) and not their json formatter.

**Comment by sirmspencer** [comment]
Ah you are right, that json.cljc is in the ajax lib.
