### ISSUE TITLE
Separate handler for :on-timeout?

### ISSUE THREAD

**Issue by Samstiles** [Day8/re-frame-http-fx#9]
Hey @danielcompton, I'm wondering if you think there's any merit to adding a separate handler specifically for if the timeout you specify is hit? Happy to submit a patch. FWIW I began using this yesterday and think it'd be useful.

**Comment by mike-thompson-day8** [comment]
@Samstiles belatedly closing.  wontfix.  We've just updated the README to be clearer about what happens in the case of timeouts.
